import type {
  MockAnalytics,
  MockChannel,
  MockConversation,
  MockRole,
  MockTenant,
  MockUser,
  MockWhatsAppOnboarding,
} from './types'

export const mockTenants: MockTenant[] = [
  {
    id: 'tenant-riyadh',
    name: 'شركة الرياض للتجارة',
    domain: 'riyadh.example.sa',
    plan: 'Enterprise',
    status: 'active',
    contacts: 12840,
    createdAt: '2025-11-12T09:30:00+03:00',
  },
  {
    id: 'tenant-jeddah',
    name: 'مجموعة جدة الرقمية',
    domain: 'jeddah.example.sa',
    plan: 'Growth',
    status: 'trial',
    contacts: 3920,
    createdAt: '2026-01-20T14:10:00+03:00',
  },
  {
    id: 'tenant-dammam',
    name: 'حلول الدمام اللوجستية',
    domain: 'dammam.example.sa',
    plan: 'Starter',
    status: 'suspended',
    contacts: 1140,
    createdAt: '2025-09-03T16:45:00+03:00',
  },
]

export const mockUsers: MockUser[] = [
  {
    id: 'user-1',
    tenantId: 'tenant-riyadh',
    name: 'أحمد المدير',
    email: 'ahmad@riyadh.example.sa',
    roleId: 'admin',
    team: 'إدارة النظام',
    status: 'active',
    lastSeenAt: '2026-05-15T09:05:00+03:00',
  },
  {
    id: 'user-2',
    tenantId: 'tenant-riyadh',
    name: 'ليلى الحسن',
    email: 'layla@riyadh.example.sa',
    roleId: 'operations-manager',
    team: 'العمليات',
    status: 'active',
    lastSeenAt: '2026-05-15T08:42:00+03:00',
  },
  {
    id: 'user-3',
    tenantId: 'tenant-riyadh',
    name: 'سعود السالم',
    email: 'saud@riyadh.example.sa',
    roleId: 'support-agent',
    team: 'الدعم',
    status: 'invited',
    lastSeenAt: '2026-05-14T21:18:00+03:00',
  },
  {
    id: 'user-4',
    tenantId: 'tenant-jeddah',
    name: 'ريم فهد',
    email: 'reem@jeddah.example.sa',
    roleId: 'whatsapp-supervisor',
    team: 'واتساب',
    status: 'active',
    lastSeenAt: '2026-05-15T07:52:00+03:00',
  },
]

export const mockRoles: MockRole[] = [
  {
    id: 'admin',
    name: 'مدير النظام',
    description: 'تحكم كامل في المنصة والصلاحيات والتكاملات.',
    usersCount: 2,
    permissions: {
      dashboard: true,
      tenants: true,
      users: true,
      roles: true,
      channels: true,
      inbox: true,
      whatsapp: true,
      reports: true,
    },
  },
  {
    id: 'operations-manager',
    name: 'مدير العمليات',
    description: 'إدارة الفرق التشغيلية والقنوات ومراجعة جودة الخدمة.',
    usersCount: 4,
    permissions: {
      dashboard: true,
      tenants: false,
      users: true,
      roles: false,
      channels: true,
      inbox: true,
      whatsapp: true,
      reports: true,
    },
  },
  {
    id: 'support-agent',
    name: 'موظف الدعم',
    description: 'متابعة المحادثات والرد على العملاء ضمن القنوات المصرح بها.',
    usersCount: 18,
    permissions: {
      dashboard: true,
      tenants: false,
      users: false,
      roles: false,
      channels: false,
      inbox: true,
      whatsapp: false,
      reports: false,
    },
  },
  {
    id: 'whatsapp-supervisor',
    name: 'مشرف واتساب',
    description: 'إشراف على إعداد واتساب والقوالب والويب هوك.',
    usersCount: 6,
    permissions: {
      dashboard: true,
      tenants: false,
      users: false,
      roles: false,
      channels: true,
      inbox: true,
      whatsapp: true,
      reports: true,
    },
  },
]

export const mockConversations: MockConversation[] = [
  {
    id: 'conv-1',
    tenantId: 'tenant-riyadh',
    customerName: 'سارة العلي',
    customerCompany: 'مؤسسة النخبة',
    customerEmail: 'sara@example.sa',
    channel: 'WhatsApp',
    status: 'جديد',
    priority: 'عاجل',
    lastMessage: 'نحتاج تفعيل رقم واتساب قبل نهاية اليوم.',
    preview: ['مرحباً، هل يمكن ربط الرقم الجديد؟', 'وصلتني رسالة خطأ من Meta.', 'نحتاج تفعيل رقم واتساب قبل نهاية اليوم.'],
    owner: 'ليلى الحسن',
    updatedAt: 'قبل 4 دقائق',
  },
  {
    id: 'conv-2',
    tenantId: 'tenant-riyadh',
    customerName: 'خالد منصور',
    customerCompany: 'شركة مدار',
    customerEmail: 'khaled@example.sa',
    channel: 'Email',
    status: 'قيد المعالجة',
    priority: 'مرتفع',
    lastMessage: 'أرسلت لكم تفاصيل التكامل عبر البريد.',
    preview: ['أريد ربط البريد بصندوق الوارد.', 'هل يمكن إضافة توقيع موحد؟', 'أرسلت لكم تفاصيل التكامل عبر البريد.'],
    owner: 'سعود السالم',
    updatedAt: 'قبل 18 دقيقة',
  },
  {
    id: 'conv-3',
    tenantId: 'tenant-jeddah',
    customerName: 'نورة فهد',
    customerCompany: 'منصة واجهة',
    customerEmail: 'noura@example.sa',
    channel: 'Web Chat',
    status: 'مغلق',
    priority: 'عادي',
    lastMessage: 'شكراً، تم حل المشكلة.',
    preview: ['لا تظهر المحادثات في لوحة الفريق.', 'تم تحديث الصلاحيات الآن.', 'شكراً، تم حل المشكلة.'],
    owner: 'ريم فهد',
    updatedAt: 'أمس',
  },
]

export const mockChannels: MockChannel[] = [
  {
    id: 'whatsapp-main',
    tenantId: 'tenant-riyadh',
    type: 'WhatsApp',
    label: 'واتساب المبيعات والدعم',
    status: 'connected',
    lastSyncAt: '2026-05-15T00:42:00+03:00',
    assignedTeam: 'فريق واتساب',
  },
  {
    id: 'email-support',
    tenantId: 'tenant-riyadh',
    type: 'Email',
    label: 'support@example.sa',
    status: 'connected',
    lastSyncAt: '2026-05-15T00:38:00+03:00',
    assignedTeam: 'فريق الدعم',
  },
  {
    id: 'web-chat',
    tenantId: 'tenant-jeddah',
    type: 'Web Chat',
    label: 'دردشة الموقع',
    status: 'needs_setup',
    lastSyncAt: '2026-05-14T22:05:00+03:00',
    assignedTeam: 'فريق العمليات',
  },
  {
    id: 'sms-alerts',
    tenantId: 'tenant-dammam',
    type: 'SMS',
    label: 'رسائل التنبيهات',
    status: 'paused',
    lastSyncAt: '2026-05-13T17:20:00+03:00',
    assignedTeam: 'فريق المنصة',
  },
]

export const mockWhatsAppOnboarding: MockWhatsAppOnboarding[] = [
  {
    tenantId: 'tenant-riyadh',
    businessNumber: '+966 55 123 4567',
    metaVerificationStatus: 'قيد المراجعة',
    webhookStatus: 'متصل',
    qrReference: 'WA-QR-2026-RUH',
    steps: [
      { id: 'business', title: 'تسجيل رقم الأعمال', description: 'تأكيد الرقم وربطه بحساب WhatsApp Business.', status: 'complete' },
      { id: 'meta', title: 'تحقق Meta', description: 'مراجعة بيانات النشاط التجاري والاسم المعروض.', status: 'in_progress' },
      { id: 'webhook', title: 'إعداد Webhook', description: 'تفعيل استقبال الرسائل والحالات من Meta Cloud API.', status: 'complete' },
      { id: 'templates', title: 'قوالب الرسائل', description: 'إعداد قوالب الترحيب والتنبيهات للمراجعة.', status: 'pending' },
    ],
  },
]

export const mockAnalytics: MockAnalytics[] = [
  {
    tenantId: 'tenant-riyadh',
    totalConversations: 1842,
    openConversations: 126,
    connectedChannels: 2,
    activeUsers: 24,
    averageResponseMinutes: 7,
    satisfactionScore: 92,
  },
  {
    tenantId: 'tenant-jeddah',
    totalConversations: 428,
    openConversations: 39,
    connectedChannels: 1,
    activeUsers: 8,
    averageResponseMinutes: 14,
    satisfactionScore: 86,
  },
]

